name: Deploy from Cursor to GitHub

on:
  # Trigger on push to main branch
  push:
    branches: [ main ]
  
  # Allow manual trigger from Actions tab
  workflow_dispatch:
  
  # Trigger on pull request to main branch
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Run tests (if available)
      run: npm test --if-present
      
    - name: Deploy to GitHub Pages (Optional)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        
    - name: Update deployment status
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🌱 EchoGarden is now live on GitHub"
        echo "📝 Repository: https://github.com/FredEcho/EchoGarden"
